version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    depends_on:
      - php
      - mysql
    env_file:
      - .env

  php:
    build:
      context: .
      dockerfile: Dockerfile_php
    volumes:
      - ./app:/var/www/html
    env_file:
      - .env

  mysql:
    build:
      context: .
      dockerfile: Dockerfile_mysql
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  php_data:
  mysql_data: