version: '3.7'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx_camagru
    container_name: nginx_camagru
    ports:
    - "8080:80"
    volumes:
    # - ./src/:/data/www/
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  
  # php:
  #   build:
  #     context: ./php
  #     dockerfile: Dockerfile
  #   image: php_camagru
  #   container_name: php_camagru
  #   volumes:
  #   - ./src/:/data/www/
