version: '3.7'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - "8080:80"
    volumes:
      - uploads:/var/www/html/uploads
    depends_on:
      - php
    env_file:
      - .env

  php:
    build:
      context: .
      dockerfile: Dockerfile_php
    volumes:
      - ./app:/var/www/html
      - uploads:/var/www/html/uploads
    env_file:
      - .env

  mysql:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql

volumes:
  mysql_data:
  uploads: